# Generated by Django 4.2.11 on 2026-03-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_image_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='description',
        ),
    ]
