# Generated by Django 4.2.11 on 2026-03-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
