# Generated by Django 4.2.11 on 2026-03-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
