# Generated by Django 4.2.11 on 2026-03-14 21:39

import auctions.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(2, 'Comment must be at least 2 characters.'), django.core.validators.MaxLengthValidator(500, 'Comment cannot exceed 500 characters.')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Description must be at least 10 characters.'), django.core.validators.MaxLengthValidator(1000, 'Description cannot exceed 1000 characters.')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4, 'Title must be at least 4 characters.'), auctions.models.validate_contains_letter]),
        ),
    ]
